<%page args="metadata" />\
# Generated by bravado-types ${metadata.bravado_types_version}
# Timestamp: ${metadata.timestamp}
% if metadata.cli_args is not None:
# CLI args: ${metadata.quoted_cli_args}
% endif
# Schema version: ${metadata.schema_version}
% if metadata.schema_origin_url:
# Schema origin url: ${metadata.schema_origin_url}
% endif
# Bravado version: ${metadata.bravado_version}
# Bravado-core version: ${metadata.bravado_core_version}
